steps:
- name: "gcr.io/cloud-builders/gcloud"
  id: first
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud deployment-manager deployments delete s-deploy || echo "delete"
- name: "gcr.io/cloud-builders/gcloud"
  id: second
  waitFor:
    - first
  args:
  - deployment-manager
  - deployments
  - create
  - s-deploy
  - --config=./deployment-manager/python/p-final/deploy_cluster.yaml
  - --automatic-rollback-on-error
- name: "gcr.io/cloud-builders/gke-deploy"
  id: third
  waitFor:
    - second
  args:
  - run
  - --filename=./deployment-manager/python/p-final/flask.yaml
  - --image=europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest
  - --location=europe-west2
  - --cluster=studyjam-cluster
images:
- "europe-west2-docker.pkg.dev/steam-kingdom-311415/gke-deploy/gke-flask:latest"
